src/S3Train.Web/Models/ProductsSearchForNameViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace S3Train.Web.Models
{
    public class ProductsSearchForNameViewModel
    {
        public Guid Id { get; set; }
        public string NameProduct { get; set; }
        public string ImagePath { get; set; }
        public string DisplayPrice { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}

src/S3Train.Web/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using S3Train.Contract;
using S3Train.Domain;
using S3Train.Web.Models;
using System;
using S3Train.DTOs;

namespace S3Train.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductDetailService _detailProductService;

        public ProductController(IProductDetailService detailProductService)
        {
            _detailProductService = detailProductService;

        }

        public ActionResult Detail(Guid id)
        {
            var prodDetail = _detailProductService.GetProductDetail(id);
            var productDetailViewModel = new ProductDetailViewModel();

                if(prodDetail.Promotion.Count() != 0)
                {
                    productDetailViewModel = new ProductDetailViewModel
                    {

                        Id = prodDetail.Id,
                        Name = prodDetail.NameProduct,
                        ImagePath = prodDetail.ImagePath,
                        DisplayPrice = $"{prodDetail.Price}",
                        Price = prodDetail.Price,
                        Rating = prodDetail.Rating ?? 0,
                        Summary = prodDetail.Summary,
                        Barcode = prodDetail.Barcode,
                        ReleaseYear = prodDetail.ReleaseYear,
                        NamePublisher = prodDetail.Publisher.NamePublisher,
                        CategoryName = prodDetail.Category.CategoryName,
                        UpdatedDate = prodDetail.UpdatedDate,
                        Amount = prodDetail.Amount,
                        PromotionPercent = prodDetail.Promotion.FirstOrDefault().PromotionPercent,
                        AuthorName = String.Join(", ", prodDetail.Author.Select(x => x.NameAuthor)),
                        RelatedProduct = prodDetail.RelatedProduct.Select(q => new ProductViewModel
                        {
                            Id = q.ProductId,
                            NameProduct = q.NameProduct,
                            ImagePath = q.ImagePath,
                            DisplayPrice = q.Price.ToString()
                        }).ToList()

                    };
                }else
                {
                productDetailViewModel = new ProductDetailViewModel
                {

                    Id = prodDetail.Id,
                    Name = prodDetail.NameProduct,
                    ImagePath = prodDetail.ImagePath,
                    DisplayPrice = $"{prodDetail.Price}",
                    Price = prodDetail.Price,
                    Rating = prodDetail.Rating ?? 0,
                    Summary = prodDetail.Summary,
                    Barcode = prodDetail.Barcode,
                    ReleaseYear = prodDetail.ReleaseYear,
                    NamePublisher = prodDetail.Publisher.NamePublisher,
                    CategoryName = prodDetail.Category.CategoryName,
                    UpdatedDate = prodDetail.UpdatedDate,
                    Amount = prodDetail.Amount,
                    AuthorName = String.Join(", ", prodDetail.Author.Select(x => x.NameAuthor)),
                    RelatedProduct = prodDetail.RelatedProduct.Select(q => new ProductViewModel
                    {
                        Id = q.ProductId,
                        NameProduct = q.NameProduct,
                        ImagePath = q.ImagePath,
                        DisplayPrice = q.Price.ToString()
                    }).ToList()

                };
            }
                
            return View(productDetailViewModel);
        }

    }

       
}

src/S3Train.Web/Controllers/ProductsSearchForNameController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using S3Train.Contract;
using S3Train.Domain;
using S3Train.Web.Models;
using System;
using PagedList;
using PagedList.Mvc;
using S3Train.DTOs;

namespace S3Train.Web.Controllers
{
    public class ProductsSearchForNameController : Controller
    {
        private readonly ISearchProductsForAuthorService _searchForAuthor;

        public ProductsSearchForNameController(ISearchProductsForAuthorService searchForAuthor)
        {
            _searchForAuthor = searchForAuthor;
        }

        public ActionResult ProductsSearchForAuthor(string Name, int page = 1, int pagesize = 8)
        {
            int totalRecord = 0;

            var productsSearchForAuthor = new HomeViewModel
            {
                productsSearchForName = GetProductsSearchForName(_searchForAuthor.GetProductsSearchForAuhtorItems(Name), ref totalRecord, page, pagesize)
            };
            ViewBag.ToTal = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling(((double)totalRecord / (double)pagesize));

            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Pre = page - 1;

            return View(productsSearchForAuthor);
        }

        private IList<ProductsSearchForNameViewModel> GetProductsSearchForName(IList<ProductDTO> proForAuthor, ref int totalRecord, int page = 1, int pagesize = 4)
        {
            var totalPro = proForAuthor.Select(x => new ProductsSearchForNameViewModel
            {
                Id = x.Id,
                ImagePath = x.ImagePath,
                NameProduct = x.NameProduct,
                DisplayPrice = $"${x.Price}",
                UpdatedDate = x.UpdatedDate,
            });

            var model = totalPro.OrderBy(x => x.NameProduct).Skip((page - 1) * pagesize).Take(pagesize).ToList();
            totalRecord = totalPro.Count();

            return model;
        }
    }
}

src/S3Train.Web/Views/ProductsSearchForName/ProductsSearchForAuthor.cshtml
@using S3Train.Web.Models;
@model HomeViewModel
@{
    ViewBag.Title = "ProductsSearchForAuthor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("ProductsSearchForAuthor", "ProductsSearchForName", FormMethod.Get))
{
    <div class="shop">
        <div class="container">
            <div class="roses-head">
                <h2>Search Results For "@Html.Value("Name")"</h2>
            </div>
        </div>
    </div>
    <!---->
    <div class="container">
        <div id="myCarousel" class="carousel slide">
            @foreach (var item in Model.productsSearchForName)
            {

                <div class="col-md-3">
                    <div class="thumbnail">

                        <a href="@Url.Action("Detail", "Product", new { @id = item.Id })">
                            <img src="@Url.Content("~/ImagePD/" + item.ImagePath)" />
                        </a>
                       @if (item.UpdatedDate == null)
                        {
                            <div class="caption">
                                <a href="@Url.Action("Detail", "Product", new { @id = item.Id })"><h5>@item.NameProduct</h5></a>
                                <p>
                                    <a class="btn btn-primary" role="button">@item.DisplayPrice</a>
                                    <a id="btn-add-to-cart" style="float:right" href="#" class="btn btn-default" role="button">Preview</a>
                                </p>

                            </div>
                           }
                           else
                           {
                            <div class="caption">
                                <a href="@Url.Action("Detail", "Product", new { @id = item.Id })"><h5>@item.NameProduct</h5></a>
                                <p><a class="btn btn-primary" role="button">@item.DisplayPrice</a><a id="btn-add-to-cart" data-id="@item.Id" style="float:right" href="#" class="btn btn-default" role="button">Add to card</a></p>
                            </div>
                           }

                    </div>
                </div>

            }
            <div class="clearfix"></div>
            <!------Page List-------->
            @if (ViewBag.TotalPage > 1)
            {
                var pageDisplay = (int)ViewBag.MaxPage;
                int totalPage = (int)ViewBag.TotalPage;
                int curentPage = ((int)ViewBag.Page);

                var startPageIndex = Math.Max(curentPage, curentPage - pageDisplay / 2);
                var endPageIndex = Math.Min(totalPage, curentPage + pageDisplay / 2);
                var link = Url.Action("ProductsSearchForAuthor", "ProductsSearchForName", new { @Name = Html.Value("Name") });
                <nav>
                    <ul class="pagination">
                        @if (curentPage > ViewBag.First)
                        {
                            <li><a href="@link&page=@ViewBag.First" title="First page"><i class="fa fa-angle-double-left"></i></a></li>
                            <li><a href="@link&page=@ViewBag.Pre" title="Previous page"><i class="fa fa-angle-left"></i></a></li>
                        }
                        @for (int i = startPageIndex; i <= endPageIndex; i++)
                        {
                        if (curentPage == i)
                        {
                                <li><a href="@link&page=@i" class="active" title="Page @i">@i</a></li>
                            }
                            else
                            {
                                <li><a href="@link&page=@i" class="pos" title="Page @i">@i</a></li>
                            }
                        }
                        @if (curentPage < totalPage)
                        {
                            <li><a href="@link&page=@ViewBag.Next" title="Next page"><i class="fa fa-angle-right"></i></a></li>
                            <li><a href="@link&page=@ViewBag.Last" title="Last page"><i class="fa fa-angle-double-right"></i></a></li>
                        }
                    </ul>
                </nav>
            }
            else
            {
                <nav>
                    <ul class="pagination">
                        <li><a href=" @Url.Action("ProductsSearchForAuthor", "ProductsSearchForName", new { @Name = Html.Value("Name") })&page=1" class="active" title="Page 1">1</a></li>
                    </ul>
                </nav>
            }
        </div>

    </div>
}

<style>
    nav ul.pagination {
        float: right;
    }
</style>