src/S3Train.Web/Areas/Admin/Controllers/ProductAdvertisementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using S3Train.Domain;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace S3Train.Web.Areas.Admin.Controllers
{
    public class ProductAdvertisementsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/ProductAdvertisements
        public ActionResult Index(int? page)
        {
            if (Session["Email"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                var productadvertisments = db.ProductAdvertisements.Include(p => p.Product);
                int pageNumber = (page ?? 1);
                int pageSize = 10;
                return View(db.ProductAdvertisements.ToList().OrderBy(t => t.CreatedDate).ToPagedList(pageNumber, pageSize));
            }
        }

        // GET: Admin/ProductAdvertisements/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductAdvertisement productAdvertisement = db.ProductAdvertisements.Find(id);
            if (productAdvertisement == null)
            {
                return HttpNotFound();
            }
            return View(productAdvertisement);
        }

        // GET: Admin/ProductAdvertisements/Create
        public ActionResult Create()
        {
            if (Session["Email"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                ViewBag.ProductId = new SelectList(db.Products, "Id", "NameProduct");
                return View();
            }
        }

        // POST: Admin/ProductAdvertisements/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "Id,ProductId,Title,Description,EventUrl,ImagePath,AdType,CreatedDate,UpdatedDate,IsActive")] ProductAdvertisement productAdvertisement, HttpPostedFileBase fileUpload)
        {
            ViewBag.ProductId = new SelectList(db.Products, "Id", "NameProduct");
            if (fileUpload == null)
            {
                ViewBag.Notification = "Choose image";
                return View();
            }

            if (ModelState.IsValid)
            {
                //Luu ten file
                var fileName = Path.GetFileName(fileUpload.FileName);
                //Luu duong dan
                var path = Path.Combine(Server.MapPath("~/ImagePD"), fileName);
                //KT HINH ANH TON TAI CHUA
                if (System.IO.File.Exists(path))
                {
                    ViewBag.Notification = "Image already exists";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                productAdvertisement.Id = Guid.NewGuid();
                productAdvertisement.ImagePath = fileName;
                db.ProductAdvertisements.Add(productAdvertisement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productAdvertisement);
        }

        // GET: Admin/ProductAdvertisements/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductAdvertisement productAdvertisement = db.ProductAdvertisements.Find(id);
            if (productAdvertisement == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductId = new SelectList(db.Products, "Id", "NameProduct");
            return View(productAdvertisement);
        }

        // POST: Admin/ProductAdvertisements/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id,ProductId,Title,Description,EventUrl,ImagePath,AdType,CreatedDate,UpdatedDate,IsActive")] ProductAdvertisement productAdvertisement, HttpPostedFileBase fileUpload)
        {
            if (ModelState.IsValid)
            {
                if (fileUpload != null)
                {
                    //Luu ten file
                    var fileName = Path.GetFileName(fileUpload.FileName);
                    //Luu duong dan
                    var path = Path.Combine(Server.MapPath("~/ImagePD"), fileName);
                    //KT HINH ANH TON TAI CHUA
                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.Notification = "Image already exists";
                    }
                    else
                    {
                        fileUpload.SaveAs(path);
                    }
                    productAdvertisement.ImagePath = fileName;
                }
                db.Entry(productAdvertisement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductId = new SelectList(db.Products, "Id", "NameProduct");
            return View(productAdvertisement);
        }

        // GET: Admin/ProductAdvertisements/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductAdvertisement productAdvertisement = db.ProductAdvertisements.Find(id);
            if (productAdvertisement == null)
            {
                return HttpNotFound();
            }
            return View(productAdvertisement);
        }

        // POST: Admin/ProductAdvertisements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ProductAdvertisement productAdvertisement = db.ProductAdvertisements.Find(id);
            db.ProductAdvertisements.Remove(productAdvertisement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/S3Train.Web/Areas/Admin/Views/ProductAdvertisements/Create.cshtml
@model S3Train.Domain.ProductAdvertisement

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2>CREATE A NEW PRODUCTADVERTISEMENT</h2>


@using (Html.BeginForm("Create", "ProductAdvertisements", FormMethod.Post, new { @enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.Label("Book", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Product, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.TextBoxFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <br />
        <div class="form-group">
            <div class="col-md-10">
                <textarea name="Description" style="width:20px">So easy!</textarea>
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.EventUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.TextBoxFor(model => model.EventUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventUrl, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="fileUpload" />
                @ViewBag.Notification
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.AdType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.EnumDropDownListFor(model => model.AdType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AdType, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.EditorFor(model => model.UpdatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    &nbsp;@Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/S3Train.Web/Areas/Admin/Views/ProductAdvertisements/Delete.cshtml
@model S3Train.Domain.ProductAdvertisement

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h3>Are you sure you want to delete this Product Advertisement?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Book
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.NameProduct)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            <img src="@Url.Content("~/ImagePD/"+Model.ImagePath)" width="50" height="50" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

src/S3Train.Web/Areas/Admin/Views/ProductAdvertisements/Details.cshtml
@model S3Train.Domain.ProductAdvertisement

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ProductAdvertisement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            <img src="@Url.Content("~/ImagePD/"+Model.ImagePath)" width="50" height="50" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/S3Train.Web/Areas/Admin/Views/ProductAdvertisements/Edit.cshtml
@model S3Train.Domain.ProductAdvertisement

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2>EDIT THIS PRODUCT ADVERTISEMENT</h2>


@using (Html.BeginForm("Edit", "ProductAdvertisements", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Book", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.TextBoxFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <br />
        <div class="form-group">
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.EventUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.TextBoxFor(model => model.EventUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventUrl, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.TextBoxFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                <input type="file" name="fileUpload"/>
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.AdType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.EnumDropDownListFor(model => model.AdType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AdType, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                &nbsp;@Html.EditorFor(model => model.UpdatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    &nbsp;@Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/S3Train.Web/Areas/Admin/Views/ProductAdvertisements/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<S3Train.Domain.ProductAdvertisement>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2>PRODUCT ADVERTISEMENTS</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered">
    <tr>
        <th>
            Book
        </th>
        <th>
            Title
        </th>
        <th>
            Description
        </th>
        <th>
            Event Url
        </th>
        <th>
            Image
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().AdType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().IsActive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Product.NameProduct)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventUrl)
        </td>
        <td>
            <img src="@Url.Content("~/ImagePD/"+item.ImagePath)" width="50" height="50" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AdType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

@*Create page link*@
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
<div class="MenuPage">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .MenuPage li {
        display: inline;
    }
</style>