src/S3Train.Web/Models/CSProductViewModel.cs
using System;

namespace S3Train.Web.Models
{
    public class CSProductViewModel
    {
        public Guid Id { get; set; }
        public string ImagePath { get; set; }
        public string NameProduct { get; set; }
        public string DisplayPrice { get; set; }
        public int Grouping { get; set; }
    }
}

src/S3Train.Web/Models/HomeViewModel.cs
using System.Collections.Generic;
using System.Linq;


namespace S3Train.Web.Models
{
    public class HomeViewModel
    {
        public IList<SliderItemViewModel> SliderItems { get; set; }
        public IEnumerable<IGrouping<int, ProductViewModel>> NewProducts { get; set; }
        public IEnumerable<IGrouping<int, CSProductViewModel>> CSProducts { get; set; }
        public IEnumerable<IGrouping<int, PromotionProductViewModel>> PromotionProducts { get; set; }
        public IList<CategoryViewModel> ProductsByCategory { get; set; }
        public IList< ProductViewModel> newProducts { get; set; }
        public IList<CSProductViewModel> csProducts { get; set; }
        public IList<PromotionProductViewModel> bestSellerProducts { get; set; }
        public IList<ProductsSearchForNameViewModel> productsSearchForName { get; set; }
        public IList<OrderProViewModel> OrderProViewModel { get; set; }
    }
}

src/S3Train.Web/Models/ProductViewModel.cs
using System;


namespace S3Train.Web.Models
{
    public class ProductViewModel
    {
        public Guid Id { get; set; }
        public string ImagePath { get; set; }
        public string NameProduct { get; set; }
        public string Summary { get; set; }
        public string DisplayPrice { get; set; }
        public string Barcode { get; set; }
        public int Rating { get; set; }
        public int Grouping { get; set; }
    }
}

src/S3Train.Web/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using S3Train.Domain;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace S3Train.Web.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Products
        public ActionResult Index(int? page)
        {
            if (Session["Email"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                var products = db.Products.Include(p => p.Category).Include(p => p.Publisher);
                int pageNumber = (page ?? 1);
                int pageSize = 10;
                return View(products.ToList().OrderBy(t => t.NameProduct).ToPagedList(pageNumber, pageSize));
            }
            
        }

        // GET: Admin/Products/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Admin/Products/Create
        public ActionResult Create()
        {
            if (Session["Email"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                ViewBag.CategoryId = new SelectList(db.Categories, "Id", "NameCategory");
                ViewBag.PublisherId = new SelectList(db.Publishers, "Id", "NamePublisher");
                return View();
            }
        }

        // POST: Admin/Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "Id,CategoryId,PublisherId,NameProduct,Summary,Price,ImagePath,Barcode,ReleaseYear,Amount,Rating,CreatedDate,UpdatedDate,IsActive")] Product product, HttpPostedFileBase fileUpload)
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "NameCategory", product.CategoryId);
            ViewBag.PublisherId = new SelectList(db.Publishers, "Id", "NamePublisher", product.PublisherId);

            if (fileUpload == null)
            {
                ViewBag.Notification = "Choose image";
                return View();
            }

            if (ModelState.IsValid)
            {
                //Luu ten file
                var fileName = Path.GetFileName(fileUpload.FileName);
                //Luu duong dan
                var path = Path.Combine(Server.MapPath("~/ImagePD"), fileName);
                //KT HINH ANH TON TAI CHUA
                if (System.IO.File.Exists(path))
                {
                    ViewBag.Notification = "Image already exists";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                product.Id = Guid.NewGuid();
                product.ImagePath = fileName;
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(product);
        }

        // GET: Admin/Products/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "NameCategory", product.CategoryId);
            ViewBag.PublisherId = new SelectList(db.Publishers, "Id", "NamePublisher", product.PublisherId);
            return View(product);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id,CategoryId,PublisherId,NameProduct,Summary,Price,ImagePath,Barcode,ReleaseYear,Amount,Rating,CreatedDate,UpdatedDate,IsActive")] Product product, HttpPostedFileBase fileUpload)
        {
            if (ModelState.IsValid)
            {
                //if (fileUpload != null)
                //{
                //    //Luu ten file
                //    var fileName = Path.GetFileName(fileUpload.FileName);
                //    //Luu duong dan
                //    var path = Path.Combine(Server.MapPath("~/ImagePD"), fileName);
                //    //KT HINH ANH TON TAI CHUA
                //    if (System.IO.File.Exists(path))
                //    {
                //        ViewBag.Notification = "Image already exists";
                //    }
                //    else
                //    {
                //        fileUpload.SaveAs(path);
                //    }
                //    product.ImagePath = fileName;
                //}
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "NameCategory", product.CategoryId);
            ViewBag.PublisherId = new SelectList(db.Publishers, "Id", "NamePublisher", product.PublisherId);
            return View(product);
        }

        // GET: Admin/Products/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/S3Train.Web/Controllers/ListOfProductsController.cs
using S3Train.Contract;
using S3Train.DTOs;
using S3Train.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace S3Train.Web.Controllers
{
    public class ListOfProductsController : Controller
    {
        private readonly IProductService _newProductsService;
        private readonly ICSProductService _cSProductsService;
        private readonly IPromotionDetailService _bestSellerProductsService;


        public ListOfProductsController(IProductService newProductsService,  ICSProductService cSProductsSerVice, IPromotionDetailService bestSellerProductsService)
        {
            _newProductsService = newProductsService;
            _cSProductsService = cSProductsSerVice;
            _bestSellerProductsService = bestSellerProductsService;
        }
        // GET: ListOfProducts
        public ActionResult NewProducts(int page = 1, int pagesize = 4)
        {
            int totalRecord = 0;

            var model = new HomeViewModel
            {
                newProducts = GetNewProducts(_newProductsService.GetNewProductItems(), ref totalRecord, page, pagesize),
            };

            ViewBag.ToTal = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling(((double)totalRecord / (double)pagesize));

            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Pre = page - 1;

            return View(model);
        }

        public ActionResult cSProducts(int page = 1, int pagesize = 4)
        {
            int totalRecord = 0;

            var csproducts = new HomeViewModel
            {
                csProducts = GetCSProducts(_cSProductsService.GetCSProductItems(), ref totalRecord, page, pagesize),
            };

            ViewBag.ToTal = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling(((double)totalRecord / (double)pagesize));

            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Pre = page - 1;

            return View(csproducts);
        }

        public ActionResult bestSellerProducts(int page = 1, int pagesize = 4)
        {
            int totalRecord = 0;
            var csproducts = new HomeViewModel
            {
                bestSellerProducts = GetBestSellerProducts(_bestSellerProductsService.GetPromotionDetail(), ref totalRecord, page, pagesize),
            };

            ViewBag.ToTal = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling(((double)totalRecord / (double)pagesize));

            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Pre = page - 1;

            return View(csproducts);
        }

        private static IList<ProductViewModel> GetNewProducts(IList<ProductDTO> products, ref int totalRecord, int page = 1, int pagesize = 4)
        {
            var totalPro = products.Select((x) => new ProductViewModel
            {
                Id = x.Id,
                ImagePath = x.ImagePath,
                NameProduct = x.NameProduct,
                DisplayPrice = $"${x.Price}",
            });

            var model = totalPro.OrderBy(x => x.NameProduct).Skip((page - 1) * pagesize).Take(pagesize).ToList();
            totalRecord = totalPro.Count();

            return model;
        }

        private static IList<CSProductViewModel> GetCSProducts(IList<ProductDTO> products, ref int totalRecord, int page = 1, int pagesize = 4)
        {
            var totalPro = products.Select((x) => new CSProductViewModel
            {
                Id = x.Id,
                ImagePath = x.ImagePath,
                NameProduct = x.NameProduct,
                DisplayPrice = $"${x.Price}",
            });

            var model = totalPro.OrderBy(x => x.NameProduct).Skip((page - 1) * pagesize).Take(pagesize).ToList();
            totalRecord = totalPro.Count();

            return model;
        }

        private static IList<PromotionProductViewModel> GetBestSellerProducts(IList<ProductDTO> promotionDetail, ref int totalRecord, int page = 1, int pagesize = 4)
        {
            var totalPro = promotionDetail.Select((x) => new PromotionProductViewModel
            {
                Id = x.ProductId,
                ImagePath = x.ImagePath,
                NameProduct = x.NameProduct,
                DisplayPrice = $"${x.Price}",
                PromotionPercent = x.Promotion.FirstOrDefault().PromotionPercent,
                Price = x.Price,
            });

            var model = totalPro.OrderBy(x => x.NameProduct).Skip((page - 1) * pagesize).Take(pagesize).ToList();
            totalRecord = totalPro.Count();

            return model;
        }
    }
}

src/S3Train.Web/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using S3Train.Contract;
using S3Train.Domain;
using S3Train.Web.Models;
using System;
using S3Train.DTOs;

namespace S3Train.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductDetailService _detailProductService;

        public ProductController(IProductDetailService detailProductService)
        {
            _detailProductService = detailProductService;

        }

        public ActionResult Detail(Guid id)
        {
            var prodDetail = _detailProductService.GetProductDetail(id);
            var productDetailViewModel = new ProductDetailViewModel();

                if(prodDetail.Promotion.Count() != 0)
                {
                    productDetailViewModel = new ProductDetailViewModel
                    {

                        Id = prodDetail.Id,
                        Name = prodDetail.NameProduct,
                        ImagePath = prodDetail.ImagePath,
                        DisplayPrice = $"{prodDetail.Price}",
                        Price = prodDetail.Price,
                        Rating = prodDetail.Rating ?? 0,
                        Summary = prodDetail.Summary,
                        Barcode = prodDetail.Barcode,
                        ReleaseYear = prodDetail.ReleaseYear,
                        NamePublisher = prodDetail.Publisher.NamePublisher,
                        CategoryName = prodDetail.Category.CategoryName,
                        UpdatedDate = prodDetail.UpdatedDate,
                        Amount = prodDetail.Amount,
                        PromotionPercent = prodDetail.Promotion.FirstOrDefault().PromotionPercent,
                        AuthorName = String.Join(", ", prodDetail.Author.Select(x => x.NameAuthor)),
                        RelatedProduct = prodDetail.RelatedProduct.Select(q => new ProductViewModel
                        {
                            Id = q.ProductId,
                            NameProduct = q.NameProduct,
                            ImagePath = q.ImagePath,
                            DisplayPrice = q.Price.ToString()
                        }).ToList()

                    };
                }else
                {
                productDetailViewModel = new ProductDetailViewModel
                {

                    Id = prodDetail.Id,
                    Name = prodDetail.NameProduct,
                    ImagePath = prodDetail.ImagePath,
                    DisplayPrice = $"{prodDetail.Price}",
                    Price = prodDetail.Price,
                    Rating = prodDetail.Rating ?? 0,
                    Summary = prodDetail.Summary,
                    Barcode = prodDetail.Barcode,
                    ReleaseYear = prodDetail.ReleaseYear,
                    NamePublisher = prodDetail.Publisher.NamePublisher,
                    CategoryName = prodDetail.Category.CategoryName,
                    UpdatedDate = prodDetail.UpdatedDate,
                    Amount = prodDetail.Amount,
                    AuthorName = String.Join(", ", prodDetail.Author.Select(x => x.NameAuthor)),
                    RelatedProduct = prodDetail.RelatedProduct.Select(q => new ProductViewModel
                    {
                        Id = q.ProductId,
                        NameProduct = q.NameProduct,
                        ImagePath = q.ImagePath,
                        DisplayPrice = q.Price.ToString()
                    }).ToList()

                };
            }
                
            return View(productDetailViewModel);
        }

    }

       
}

src/S3Train.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/S3Train.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/S3Train.Web/Views/Home/Index.cshtml
@using S3Train.Web.Models;
@model HomeViewModel

@{
    ViewBag.Title = "Home Page";
}


<div class="container">

    @{
        Html.RenderPartial("_HomeSlider", Model.SliderItems);
    }
    <div class="product">
        <div class="products">
            <h5 class="latest-product">NEW BOOK</h5>
            <a class="view-all" href="@Url.Action("NewProducts", "ListOfProducts", null)">SEE MORE<span></span></a>
        </div>
        <div class="clearfix"> </div>
        <div class="container">
            <div class="row">
                <div class="well">
                    <!-- Carousel ================================================== -->
                    <div id="myCarousel" class="carousel slide">
                        @Html.Partial("_NewProduct", Model.NewProducts)
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="fa fa-chevron-left fa-2x"></i></a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="fa fa-chevron-right fa-2x"></i></a>

                    </div><!-- End Carousel -->
                </div><!-- End Well -->
            </div>
        </div>
        <div class="products">
            <h5 class="latest-product">BOOK COMING SOON</h5>
            <a class="view-all" href="@Url.Action("cSProducts", "ListOfProducts", null)">SEE MORE<span> </span></a>
        </div>
        <div class="clearfix"> </div>

        <div class="container">
            <div class="row">
                <div class="well">
                    <!-- Carousel
                    ================================================== -->
                    <div id="myCarousel1" class="carousel slide">
                        @Html.Partial("_CSProduct", Model.CSProducts)
                        <a class="left carousel-control" href="#myCarousel1" data-slide="prev"><i class="fa fa-chevron-left fa-2x"></i></a>
                        <a class="right carousel-control" href="#myCarousel1" data-slide="next"><i class="fa fa-chevron-right fa-2x"></i></a>

                    </div><!-- End Carousel -->
                </div><!-- End Well -->
            </div>
        </div>
        <div class="clearfix"> </div>

        <div class="products">
            <h5 class="latest-product">BEST SELLER</h5>
            <a class="view-all" href="@Url.Action("bestSellerProducts", "ListOfProducts", null)">SEE MORE<span> </span></a>
        </div>
        <div class="clearfix"> </div>

        <div class="container">
            <div class="row">
                <div class="well">
                    <!-- Carousel
                    ================================================== -->
                    <div id="myCarousel2" class="carousel slide">
                        @Html.Partial("_PromotionProduct", Model.PromotionProducts)
                        <a class="left carousel-control" href="#myCarousel2" data-slide="prev"><i class="fa fa-chevron-left fa-2x"></i></a>
                        <a class="right carousel-control" href="#myCarousel2" data-slide="next"><i class="fa fa-chevron-right fa-2x"></i></a>

                    </div><!-- End Carousel -->
                </div><!-- End Well -->
            </div>
        </div>
        <div class="clearfix"> </div>

    </div>
    <div class="clearfix"> </div>

    <script>
    $('#myCarousel').carousel({
        interval: 0
    });
    $('#myCarousel1').carousel({
        interval: 0
    });
    $('#myCarousel2').carousel({
        interval: 0
    });
    $('#myCarousel3').carousel({
        interval: 0
    });
    </script>
</div>

src/S3Train.Web/Views/Home/_CSProduct.cshtml
@using S3Train.Web.Models;
@model IEnumerable<IGrouping<int, CSProductViewModel>>
@{
    ViewBag.Title = "_CSProduct";
}

<div class="carousel-inner">
    @{
        foreach (var group in Model)
        {
            var activeClass = group.Key == 0 ? "active" : string.Empty;
            <div class="item @activeClass">
                <div class="row">
                    @foreach (var item in group)
                    {

                        <div class="col-md-3">
                            <div class="thumbnail">

                                <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )">
                                    <img src="@Url.Content("~/ImagePD/"+item.ImagePath)" />
                                </a>
                                <div class="caption">
                                    <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )"><h5>@item.NameProduct</h5></a>
                                    <p><a  class="btn btn-primary" role="button">@item.DisplayPrice</a><a id="btn-add-to-cart1" style="float:right"  class="btn btn-default" role="button">Preview</a></p>
                                </div>

                            </div>
                        </div>

                    }

                </div>
            </div>
        }
    }

</div>

src/S3Train.Web/Views/Home/_Categories.cshtml
@*@using S3Train.Models;
@model HomeViewModel

@foreach (var item in Model.CategoryItems)
{
    <li><a href="/Category1/@item.MetaTitle-@item.CategoryId" title='Home'><span>@item.NameCategory</span></a></li>
}*@

src/S3Train.Web/Views/Home/_HomeSlider.cshtml
@using S3Train.Web.Models;
@model IList<SliderItemViewModel>


<div class="container">
    <div class="shoes-grid">
        <a href="#">
            <div class="wrap-in">
               
                <div class="wmuSlider example1 slide-grid">
                    @{
                        foreach (var item in Model)
                        {
                            
                            <div class="wmuSliderWrapper">

                                <article style="position: absolute; width: 100%; opacity: 0;">
                                    
                                    <div class="banner-matter">
                                        <a href="@Url.Action("Detail", "Product",new { @id = item.ProductId} )">
                                            <div class="col-md-5 banner-bag">

                                                <img class="img-responsive " src="@Url.Content("~/ImagePD/"+@item.ImagePath)" alt=" " />

                                            </div>
                                            <div class="col-md-7 banner-off">
                                                <h5>@item.Title</h5>
                                                <label>FOR ALL PURCHASE <b>VALUE</b></label>
                                                <p>@item.Description </p>
                                                <span class="on-get">@item.EventUrl</span>
                                            </div>

                                            <div class="clearfix"> </div>
                                        </a>
                                    </div>

                                </article>

                            </div>
                        }
                    }
                    </div>
                </div>
</a>
        @*<ul class="wmuSliderPagination">
            <li><a href="#" class="">0</a></li>
            <li><a href="#" class="">1</a></li>
            <li><a href="#" class="">2</a></li>
            <li><a href="#" class="">3</a></li>
            <li><a href="#" class="">4</a></li>
        </ul>*@
        <script src="~/Content/js/jquery.wmuSlider.js"></script>
        <script>
            $('.example1').wmuSlider();
        </script>
    </div>
</div>

src/S3Train.Web/Views/Home/_NewProduct.cshtml
@using S3Train.Web.Models;
@model IEnumerable<IGrouping<int, ProductViewModel>>
@{
    ViewBag.Title = "_NewProduct";
}
<div class="carousel-inner">
    @{
        foreach (var group in Model)
        {
            var activeClass = group.Key == 0 ? "active" : string.Empty;
            <div class="item @activeClass">
                <div class="row">
                    @foreach (var item in group)
                    {

                        <div class="col-md-3">
                            <div class="thumbnail">

                                <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )">
                                    <img src="@Url.Content("~/ImagePD/"+item.ImagePath)" />
                                </a>
                                <div class="caption">
                                    <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )"><h5>@item.NameProduct</h5></a>
                                    <p><a class="btn btn-primary" role="button">@item.DisplayPrice</a><a id="btn-add-to-cart" data-id="@item.Id" style="float:right"  class="btn btn-default" role="button" onclick="myFunction()">Add to card</a></p>
                                    <div id="snackbar">Add to cart successfully</div>
                                </div>

                            </div>
                        </div>

                    }

                </div>
            </div>
        }
    }

</div>
<script>
    $(document).ready(function () {
        $('.btn-default').click(function () {
            var id = $(this).data("id");
            $.ajax({
                type: "POST",
                url: '/Cart/AddItems',
                data: { Id: id },
                success: function (data) {
                }
            });
        });
    });
    function myFunction() {
      // Get the snackbar DIV
      var x = document.getElementById("snackbar");

      // Add the "show" class to DIV
      x.className = "show";

      // After 3 seconds, remove the show class from DIV
        setTimeout(function () { x.className = x.className.replace("show", ""); }, 5000);
    }
</script>

src/S3Train.Web/Views/Home/_PromotionProduct.cshtml
@using S3Train.Web.Models;
@model IEnumerable<IGrouping<int, PromotionProductViewModel>>
@{
    ViewBag.Title = "_PromotionProduct";
}

<div class="carousel-inner">
    @{
        foreach (var group in Model)
        {
            var activeClass = group.Key == 0 ? "active" : string.Empty;
            <div class="item @activeClass">
                <div class="row">
                    @foreach (var item in group)
                    {

                        <div class="col-md-3">
                            <div class="thumbnail">

                                <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )">
                                    <img src="@Url.Content("~/ImagePD/"+item.ImagePath)" />
                                </a>
                                <div class="caption">
                                    <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )"><h5>@item.NameProduct</h5></a>
                                    <p>
                                        <a id="btn-add-to-cart" class="btn btn-primary" role="button">$@(Convert.ToDouble(item.Price) - (Convert.ToDouble(item.Price) * item.PromotionPercent / 100))</a>
                                        <a id="btn-add-to-cart" data-id="@item.Id" style="float:right" class="btn btn-default" role="button" onclick="myFunction()">Add to card</a>
                                    </p>
                                    <div id="snackbar">Add to cart successfully</div>
                                </div>

                            </div>
                        </div>

                    }

                </div>
            </div>
        }
    }

</div>